const evidence={
register:{kicker:'DOCUMENT 01',title:'Night Register',body:'Four entries were written between 21:40 and 00:20. The first three press unevenly into the paper. The final line is unusually neat.',observation:'A name in the register proves only that someone wrote it down.',clueTitle:'Four names, one suspicious line',clueText:"Elias Vale's entry looks different from the first three.",visual:`<div class="doc-register"><div class="row"><strong>Hana Mori</strong><span>203</span><span>21:40</span></div><div class="row"><strong>Leon Bell</strong><span>108</span><span>22:15</span></div><div class="row"><strong>Clara Weiss</strong><span>206</span><span>23:05</span></div><div class="row"><strong>Elias Vale</strong><span>214</span><span>00:20</span></div></div>`},
keys:{kicker:'OBJECT 02',title:'Room Key Board',body:'Rooms 108, 203, and 206 have empty hooks. Their keys were taken. Room 214 still has its brass key hanging in place.',observation:'If Elias Vale checked into Room 214, why was the room key never removed?',clueTitle:'Room 214 key still present',clueText:'Keys 108, 203 and 206 are gone. 214 is still on the board.',visual:`<div class="key-visual"><div class="key-tag missing">108<br><small>empty hook</small></div><div class="key-tag missing">203<br><small>empty hook</small></div><div class="key-tag missing">206<br><small>empty hook</small></div><div class="key-tag">214<br><small>key present</small></div></div>`},
note:{kicker:'DOCUMENT 03',title:"Porter's Note",body:'A note written by the night porter before he left the desk at 00:45.',observation:'The note records three arrivals. It also says the east wing is shut.',clueTitle:'Only three arrivals',clueText:'The porter counted three guests entering before 00:45.',visual:`<div class="note-visual">11:58 — kettle still broken.<br>Three late arrivals total.<br>East wing stays shut. Do not issue those keys.<br>— M.</div>`},
paper:{kicker:'DOCUMENT 04',title:'The Harbor Gazette',body:"Yesterday's local paper reports a burst water main inside the hotel. Rooms 210 through 218 are closed until repairs are completed.",observation:'Room 214 is inside the closed section.',clueTitle:'Room 214 is in a closed wing',clueText:'Rooms 210–218 were officially closed before tonight.',visual:`<div class="paper-visual"><h3>THE HARBOR GAZETTE</h3><p><strong>WATER MAIN BURST CLOSES HOTEL EAST WING</strong></p><p>Management confirmed that rooms 210–218 will remain inaccessible until Friday morning following damage to the second-floor pipework.</p></div>`},
letter:{kicker:'DOCUMENT 05',title:'Unsent Letter',body:'The envelope is addressed to Elias Vale. It was returned to the front desk because no guest by that name had collected it.',observation:'Inside, the sender writes: “I will meet you here on Friday.” Tonight is Thursday.',clueTitle:'Elias was expected tomorrow',clueText:'A letter says Elias Vale was due to arrive Friday, not Thursday.',visual:`<div class="letter-visual">Elias —<br><br>I checked the reservation. Friday is still good. I'll meet you in the lobby after six.<br><br>Don't arrive early. The east wing is a mess.<br><br>— S.</div>`},
photo:{kicker:'OBJECT 06',title:'Lobby Photograph',body:'A disposable camera photo from the lobby clocked at 00:32. Three late guests are visible: a woman with a red scarf, a man carrying a sample case, and a woman holding a violin case.',observation:'Those details match Hana Mori, Leon Bell, and Clara Weiss. There is no fourth guest in frame.',clueTitle:'Three people in the lobby',clueText:'The 00:32 photograph shows the other three registered guests.',visual:`<div class="photo-visual"><span class="guest g1"></span><span class="guest g2"></span><span class="guest g3"></span></div>`}
};
const found=new Set();
const $=id=>document.getElementById(id);
const overlay=$('overlay'),accuseOverlay=$('accuseOverlay'),endingOverlay=$('endingOverlay'),clueList=$('clueList'),count=$('count'),accuseBtn=$('accuseBtn'),unlockText=$('unlockText');
let audioCtx=null,hum=null,humGain=null;
function clickSound(freq=180,duration=.04){if(!audioCtx)return;const osc=audioCtx.createOscillator(),gain=audioCtx.createGain();osc.type='triangle';osc.frequency.value=freq;gain.gain.setValueAtTime(.035,audioCtx.currentTime);gain.gain.exponentialRampToValueAtTime(.0001,audioCtx.currentTime+duration);osc.connect(gain).connect(audioCtx.destination);osc.start();osc.stop(audioCtx.currentTime+duration)}
function toggleSound(){if(!audioCtx){audioCtx=new(window.AudioContext||window.webkitAudioContext)();hum=audioCtx.createOscillator();humGain=audioCtx.createGain();hum.type='sine';hum.frequency.value=48;humGain.gain.value=.012;hum.connect(humGain).connect(audioCtx.destination);hum.start();document.body.classList.add('sound-on');$('soundBtn').textContent='sound: on';clickSound(240,.06)}else{const on=document.body.classList.toggle('sound-on');humGain.gain.value=on?.012:0;$('soundBtn').textContent=`sound: ${on?'on':'off'}`;if(on)clickSound(240,.06)}}
function renderClues(){count.textContent=String(found.size);clueList.innerHTML=found.size?[...found].map(key=>`<div class="clue"><strong>${evidence[key].clueTitle}</strong><span>${evidence[key].clueText}</span></div>`).join(''):'<p class="empty-state">Nothing recorded yet.</p>';accuseBtn.disabled=found.size<4;unlockText.textContent=found.size<4?`Find ${4-found.size} more piece${4-found.size===1?'':'s'} of evidence.`:found.size<6?'You can conclude now, or inspect the rest.':'All evidence collected.'}
function openEvidence(key){const item=evidence[key];$('evidenceKicker').textContent=item.kicker;$('evidenceTitle').textContent=item.title;$('evidenceVisual').innerHTML=item.visual;$('evidenceBody').textContent=item.body;$('evidenceObservation').textContent=item.observation;found.add(key);renderClues();overlay.hidden=false;document.body.style.overflow='hidden';$('closeOverlay').focus();clickSound(150,.05)}
function closeEvidence(){overlay.hidden=true;document.body.style.overflow=''}
function openAccuse(){if(accuseBtn.disabled)return;accuseOverlay.hidden=false;document.body.style.overflow='hidden';$('closeAccuse').focus();clickSound(120,.06)}
function closeAccusation(){accuseOverlay.hidden=true;document.body.style.overflow=''}
function resolveAccusation(suspect){accuseOverlay.hidden=true;endingOverlay.hidden=false;if(suspect==='elias'){$('endingKicker').textContent='CASE CLOSED';$('endingTitle').textContent='Elias Vale never checked in.';$('endingBody').textContent='The room key never left the board. Room 214 was closed. The porter counted only three arrivals. The photograph confirms those three. The final register line was added after the fact—by someone expecting Elias tomorrow. At 02:19 the phone rings again. This time, no one speaks.';clickSound(240,.18)}else{$('endingKicker').textContent='UNRESOLVED';$('endingTitle').textContent='The evidence does not hold.';$('endingBody').textContent="That guest is supported by the physical record. Something about your conclusion is wrong. The desk clock advances to 02:18.";clickSound(90,.18)}}
function resetGame(){found.clear();renderClues();overlay.hidden=true;accuseOverlay.hidden=true;endingOverlay.hidden=true;document.body.style.overflow='';window.scrollTo({top:0,behavior:'smooth'})}
document.querySelectorAll('.scene-object').forEach(b=>b.addEventListener('click',()=>openEvidence(b.dataset.evidence)));
document.querySelectorAll('.suspect').forEach(b=>b.addEventListener('click',()=>resolveAccusation(b.dataset.suspect)));
$('closeOverlay').addEventListener('click',closeEvidence);$('closeAccuse').addEventListener('click',closeAccusation);accuseBtn.addEventListener('click',openAccuse);$('endingBtn').addEventListener('click',()=>{endingOverlay.hidden=true;document.body.style.overflow=''});$('resetBtn').addEventListener('click',resetGame);$('soundBtn').addEventListener('click',toggleSound);
overlay.addEventListener('click',e=>{if(e.target===overlay)closeEvidence()});accuseOverlay.addEventListener('click',e=>{if(e.target===accuseOverlay)closeAccusation()});
document.addEventListener('keydown',e=>{if(e.key!=='Escape')return;if(!endingOverlay.hidden){endingOverlay.hidden=true;document.body.style.overflow=''}else if(!accuseOverlay.hidden)closeAccusation();else if(!overlay.hidden)closeEvidence()});
renderClues();
