const UI={zh:{objective:'目标',hint:'提示',check:'验证',reset:'重置',next:'返回语言选择',route:'中文路线',done:'逃脱成功',complete:'你让汉字改变了牢房。',feature:'中文路线利用了汉字的字形结构、组合关系和词义。这里的“字”不仅表示东西，也可以直接成为东西。',answer:'组合区',soundOn:'声音 开',soundOff:'声音 关',languages:'语言'},ja:{objective:'目的',hint:'ヒント',check:'確かめる',reset:'やり直す',next:'言語選択へ',route:'日本語ルート',done:'脱出成功',complete:'文字の仕組みそのものを使って、部屋を抜け出した。',feature:'日本語ルートでは、漢字の構成・熟語・かなの並びを利用する。意味だけでなく、表記体系そのものが仕掛けになる。',answer:'組み立て',soundOn:'音 ON',soundOff:'音 OFF',languages:'言語'},en:{objective:'OBJECTIVE',hint:'HINT',check:'CHECK',reset:'RESET',next:'BACK TO LANGUAGES',route:'ENGLISH ROUTE',done:'YOU ESCAPED',complete:'You changed the room by changing the words.',feature:'The English route uses spacing, anagrams, and the fact that a new arrangement of the same letters can produce a completely different instruction.',answer:'BUILD HERE',soundOn:'SOUND ON',soundOff:'SOUND OFF',languages:'LANGUAGES'},de:{objective:'ZIEL',hint:'HINWEIS',check:'PRÜFEN',reset:'ZURÜCKSETZEN',next:'ZUR SPRACHAUSWAHL',route:'DEUTSCHER WEG',done:'ENTKOMMEN',complete:'Du hast die Regeln des Raumes durch Wortbildung verändert.',feature:'Der deutsche Weg nutzt besonders Komposita und trennbare Verben. Wörter können sich zu sehr präzisen neuen Begriffen zusammensetzen.',answer:'HIER BAUEN',soundOn:'TON AN',soundOff:'TON AUS',languages:'SPRACHEN'},fr:{objective:'OBJECTIF',hint:'INDICE',check:'VÉRIFIER',reset:'RÉINITIALISER',next:'RETOUR AUX LANGUES',route:'PARCOURS FRANÇAIS',done:'VOUS ÊTES SORTI',complete:'Vous avez modifié la phrase, puis la réalité.',feature:"Le parcours français joue avec la négation discontinue, l'accent et l'apostrophe : de petits signes graphiques peuvent complètement changer la fonction d'une phrase.",answer:'ASSEMBLER ICI',soundOn:'SON ON',soundOff:'SON OFF',languages:'LANGUES'},es:{objective:'OBJETIVO',hint:'PISTA',check:'COMPROBAR',reset:'REINICIAR',next:'VOLVER A IDIOMAS',route:'RUTA ESPAÑOLA',done:'HAS ESCAPADO',complete:'Cambiaste las palabras y con ellas cambió la habitación.',feature:'La ruta española usa negación, anagramas e imperativos. Una pequeña reorganización puede convertir la inmovilidad en una orden de movimiento.',answer:'CONSTRUIR AQUÍ',soundOn:'SONIDO ON',soundOff:'SONIDO OFF',languages:'IDIOMAS'}};

const LANGS={zh:{native:'中文',route:'字形与字义',mechanic:'拆字 · 合字 · 词义',desc:'让汉字的结构直接成为机关。'},ja:{native:'日本語',route:'漢字とかな',mechanic:'漢字構成 · 熟語 · 表記',desc:'同じ文字体系でも、日本語では別の手触りになる。'},en:{native:'English',route:'Letters & spacing',mechanic:'anagram · spacing · wordplay',desc:'Move letters, not meanings.'},de:{native:'Deutsch',route:'Wortbau',mechanic:'Komposita · trennbare Verben',desc:'Build new objects by building new words.'},fr:{native:'Français',route:'Petits signes',mechanic:'négation · accent · apostrophe',desc:'Tiny marks can change the sentence.'},es:{native:'Español',route:'Movimiento',mechanic:'negación · anagrama · imperativo',desc:'Reorder language until it becomes an instruction.'}};

const LEVELS={
zh:[
{title:'第一室：困',prompt:'你被「困」在这里。',objective:'把困住你的东西移出边界。',hint:'「困」里面是谁被关住了？',type:'remove',tokens:['囗','木'],removable:[1],answer:['囗'],success:'木离开了边界。『困』不再成立。墙出现了一条缝。',explain:'「困」可以看作木被围在框中。这里把字形本身当成空间。'},
{title:'第二室：明',prompt:'房间没有灯。墙上只有「日」和「月」。',objective:'把两个字合成一个能让房间亮起来的字。',hint:'日与月放在一起，会成为什么？',type:'build',tokens:['日','月','火'],answer:['日','月'],displayAnswer:'明',success:'『明』出现。房间亮了，门的位置终于可见。',explain:'「明」由日、月构成。这里利用的是汉字的合字结构。'},
{title:'第三室：出口',prompt:'门上没有把手，只有几个可移动的字。',objective:'组成一个能真正离开这里的词。',hint:'不是「入口」。',type:'build',tokens:['出','入','口'],answer:['出','口'],displayAnswer:'出口',success:'『出口』完成。文字向两侧分开，露出真正的门。',explain:'最后一关让词义直接成为空间中的功能。'}],
ja:[
{title:'第一室：休',prompt:'壁には「人」と「木」だけが残されている。',objective:'疲れた「人」を休ませる一字を作る。',hint:'人が木のそばに寄ると？',type:'build',tokens:['人','木','石'],answer:['人','木'],displayAnswer:'休',success:'「休」が現れ、監視灯が一瞬消える。',explain:'「休」は亻（人）と木から成る。漢字の構成そのものを仕掛けにした。'},
{title:'第二室：明',prompt:'廊下は暗い。「日」と「月」が別々に置かれている。',objective:'二つを合わせ、反対の状態を作る。',hint:'暗いなら、必要なのは「明」。',type:'build',tokens:['月','日','闇'],answer:['日','月'],displayAnswer:'明',success:'「明」。非常口の標識が浮かび上がる。',explain:'同じ漢字でも、日本語では「明るい」という語感につながる。'},
{title:'第三室：出口',prompt:'標識には「入口」とある。だが、こちら側から入る必要はない。',objective:'「入口」を「出口」に変える。',hint:'一字だけ、役割を変えればいい。',type:'replace',tokens:['入','出'],sentence:['入','口'],target:['出','口'],success:'標識が「出口」に変わり、扉のロックが外れる。',explain:'「入口／出口」が対になる熟語。文字一つの置換が空間の向きを変える。'}],
en:[
{title:'ROOM ONE: NOWHERE',prompt:'The wall says NOWHERE.',objective:'Change where you are without changing any letters.',hint:'The prison may be a spacing problem.',type:'choice',options:['NOWHERE','NOW HERE','NO WHERE'],answer:'NOW HERE',success:'NOWHERE becomes NOW HERE. The room acknowledges your presence.',explain:'English spacing can turn the same sequence of letters into a different statement.'},
{title:'ROOM TWO: SILENT',prompt:'The lock displays SILENT.',objective:'Rearrange the letters into an instruction.',hint:'Use your ears.',type:'build',tokens:['S','I','L','E','N','T'],answer:['L','I','S','T','E','N'],displayAnswer:'LISTEN',success:'LISTEN. A soft click comes from behind the left wall.',explain:'SILENT and LISTEN are anagrams: the same letters, a different command.'},
{title:'ROOM THREE: EXIT',prompt:'A voice says: TURN THE KEY. There is no key, only letters.',objective:'Build the word that describes what you need most.',hint:'You are not looking for a key. You are looking for a way out.',type:'build',tokens:['E','X','I','T','K','Y'],answer:['E','X','I','T'],displayAnswer:'EXIT',success:'EXIT appears. The word becomes a sign, then a doorway.',explain:'The final English puzzle is deliberately literal: the label becomes the object.'}],
de:[
{title:'RAUM EINS: NOTAUSGANG',prompt:'An der Wand steht nur AUSGANG. Er bleibt verschlossen.',objective:'Bilde den besonderen Ausgang, der sich im Notfall öffnen muss.',hint:'Deutsch liebt zusammengesetzte Wörter.',type:'build',tokens:['NOT','AUSGANG','HAUS','TÜR'],answer:['NOT','AUSGANG'],displayAnswer:'NOTAUSGANG',success:'NOTAUSGANG. Das Schild leuchtet grün.',explain:'Deutsche Komposita bauen einen neuen, präzisen Begriff aus mehreren Wörtern.'},
{title:'RAUM ZWEI: AUFMACHEN',prompt:'DIE TÜR BLEIBT ZU.',objective:'Bilde das Verb, das die Tür öffnen soll.',hint:'AUF + MACHEN.',type:'build',tokens:['AUF','MACHEN','ZU','GEHEN'],answer:['AUF','MACHEN'],displayAnswer:'AUFMACHEN',success:'AUFMACHEN. Die Verriegelung springt auf.',explain:'„aufmachen“ ist ein trennbares Verb; seine Teile können im Satz auseinanderliegen, gehören aber zusammen.'},
{title:'RAUM DREI: FREIHEIT',prompt:'Auf dem Boden liegt das Wort FREI. Daneben: HEIT.',objective:'Mach aus einem Zustand etwas Größeres.',hint:'Ein Suffix kann aus einem Adjektiv ein Substantiv machen.',type:'build',tokens:['FREI','HEIT','LOS','KEIT'],answer:['FREI','HEIT'],displayAnswer:'FREIHEIT',success:'FREIHEIT. Die letzte Wand verliert ihre Bedeutung.',explain:'Mit dem Suffix -heit wird aus „frei“ das Substantiv „Freiheit“.'}],
fr:[
{title:'SALLE UNE : TU NE SORS PAS',prompt:'La porte affirme : TU NE SORS PAS.',objective:'Retire ce qui transforme la sortie en interdiction.',hint:'La négation française encadre souvent le verbe.',type:'remove',tokens:['TU','NE','SORS','PAS'],removable:[1,3],answer:['TU','SORS'],success:'TU SORS. La phrase cesse d’interdire le mouvement.',explain:'La négation standard « ne ... pas » entoure le verbe. Retirer les deux éléments renverse le sens.'},
{title:'SALLE DEUX : OU / OÙ',prompt:'Le mur demande : OU EST LA SORTIE ?',objective:'Ajoute le signe qui transforme une alternative en une question de lieu.',hint:'Il manque un accent.',type:'choice',options:['OU','OÙ','ÔU'],answer:'OÙ',success:'OÙ EST LA SORTIE ? Une flèche apparaît sous la phrase.',explain:'« ou » signifie « or », tandis que « où » indique le lieu. Un seul accent change la fonction du mot.'},
{title:"SALLE TROIS : L’ISSUE",prompt:"Deux fragments flottent : L’ et ISSUE.",objective:'Assemble l’expression qui peut désigner la sortie.',hint:'L’apostrophe rapproche l’article du nom.',type:'build',tokens:["L’",'ISSUE','LA','PORTE'],answer:["L’",'ISSUE'],displayAnswer:"L’ISSUE",success:'L’ISSUE. Le mot devient littéralement une issue.',explain:'« issue » peut désigner une sortie. L’élision de l’article devant une voyelle donne « l’issue ».'}],
es:[
{title:'SALA UNO: SIN SALIDA',prompt:'La pared dice SIN SALIDA.',objective:'Quita lo que convierte la salida en ausencia de salida.',hint:'Una sola palabra niega la posibilidad.',type:'remove',tokens:['SIN','SALIDA'],removable:[0],answer:['SALIDA'],success:'SALIDA. La pared deja de ser un callejón sin salida.',explain:'« sin salida » significa que no hay salida; al quitar « sin », queda exactamente lo que necesitas.'},
{title:'SALA DOS: NADA',prompt:'En el suelo aparece NADA.',objective:'Reordena las mismas letras para convertir la nada en una orden de movimiento.',hint:'Camina.',type:'build',tokens:['N','A','D','A'],answer:['A','N','D','A'],displayAnswer:'ANDA',success:'ANDA. El suelo se convierte en un pasillo.',explain:'NADA y ANDA usan las mismas letras. « Anda » funciona como una orden coloquial para moverse.'},
{title:'SALA TRES: SALIR',prompt:'La última puerta solo entiende verbos.',objective:'Construye el verbo que describe tu acción final.',hint:'No necesitas « salida » ahora. Necesitas la acción.',type:'build',tokens:['SAL','IR','ENT','RAR'],answer:['SAL','IR'],displayAnswer:'SALIR',success:'SALIR. La palabra desaparece y tú también.',explain:'« salir » es el verbo; « salida » es el sustantivo. La ruta termina transformando un lugar en una acción.'}]};

const $=id=>document.getElementById(id),menuView=$('menuView'),gameView=$('gameView'),completeView=$('completeView'),languageGrid=$('languageGrid'),routeLabel=$('routeLabel'),roomTitle=$('roomTitle'),progressText=$('progressText'),progressBar=$('progressBar'),promptEl=$('prompt'),stage=$('stage'),message=$('message'),objectiveLabel=$('objectiveLabel'),objective=$('objective'),hintLabel=$('hintLabel'),hintBtn=$('hintBtn'),hintText=$('hintText'),checkBtn=$('checkBtn'),resetBtn=$('resetBtn'),homeBtn=$('homeBtn'),soundBtn=$('soundBtn'),completeKicker=$('completeKicker'),completeTitle=$('completeTitle'),completeBody=$('completeBody'),languageFeature=$('languageFeature'),nextRouteBtn=$('nextRouteBtn');
let lang='zh',levelIndex=0,state={},audioCtx=null,soundEnabled=false;
function tone(freq=220,dur=.06){if(!soundEnabled)return;if(!audioCtx)audioCtx=new(window.AudioContext||window.webkitAudioContext)();const o=audioCtx.createOscillator(),g=audioCtx.createGain();o.type='triangle';o.frequency.value=freq;g.gain.setValueAtTime(.035,audioCtx.currentTime);g.gain.exponentialRampToValueAtTime(.0001,audioCtx.currentTime+dur);o.connect(g).connect(audioCtx.destination);o.start();o.stop(audioCtx.currentTime+dur)}
function show(v){menuView.hidden=v!=='menu';gameView.hidden=v!=='game';completeView.hidden=v!=='complete'}
function buildMenu(){languageGrid.innerHTML='';Object.entries(LANGS).forEach(([code,item])=>{const b=document.createElement('button');b.className='language-card';b.type='button';b.innerHTML=`<span class="native">${item.native}</span><span class="route-name">${item.route}</span><span class="mechanic">${item.mechanic}<br>${item.desc}</span>`;b.addEventListener('click',()=>startRoute(code));languageGrid.appendChild(b)})}
function startRoute(code){lang=code;levelIndex=0;document.body.className=`lang-${code}`;show('game');renderLevel();tone(190,.08)}
function applyUI(){const u=UI[lang];objectiveLabel.textContent=u.objective;hintLabel.textContent=u.hint;checkBtn.textContent=u.check;resetBtn.textContent=u.reset;routeLabel.textContent=u.route;homeBtn.textContent=u.languages;soundBtn.textContent=soundEnabled?u.soundOn:u.soundOff}
function renderLevel(){applyUI();const l=LEVELS[lang][levelIndex];state={selected:[],removed:new Set(),choice:null,replace:null};roomTitle.textContent=l.title;promptEl.textContent=l.prompt;objective.textContent=l.objective;hintText.textContent=l.hint;hintText.hidden=true;message.textContent='';message.className='message';progressText.textContent=`${levelIndex+1} / ${LEVELS[lang].length}`;progressBar.style.width=`${((levelIndex+1)/LEVELS[lang].length)*100}%`;stage.innerHTML='';checkBtn.disabled=false;resetBtn.disabled=false;if(l.type==='build')renderBuild(l);if(l.type==='remove')renderRemove(l);if(l.type==='choice')renderChoice(l);if(l.type==='replace')renderReplace(l)}
function token(t,i,small=false){const b=document.createElement('button');b.type='button';b.className='token'+(small?' small':'');b.textContent=t;b.dataset.index=i;return b}
function renderBuild(l){const pool=document.createElement('div'),ans=document.createElement('div');pool.className='token-zone';ans.className='answer-zone';ans.dataset.label=UI[lang].answer;l.tokens.forEach((t,i)=>{const b=token(t,i);b.addEventListener('click',()=>{if(b.classList.contains('used'))return;b.classList.add('used');state.selected.push({i,text:t});const c=token(t,i,true);c.addEventListener('click',()=>{const p=state.selected.findIndex(x=>x.i===i);if(p>=0)state.selected.splice(p,1);b.classList.remove('used');c.remove();tone(150,.04)});ans.appendChild(c);tone(260,.04)});pool.appendChild(b)});stage.append(pool,ans);if(l.displayAnswer){const n=document.createElement('div');n.className='annotation';n.textContent='→ ?';stage.appendChild(n)}}
function renderRemove(l){const s=document.createElement('div');s.className='sentence-zone';l.tokens.forEach((t,i)=>{const b=token(t,i,true);if(l.removable.includes(i))b.addEventListener('click',()=>{state.removed.has(i)?state.removed.delete(i):state.removed.add(i);b.classList.toggle('removed');tone(170,.04)});s.appendChild(b)});const n=document.createElement('div');n.className='annotation';n.textContent='Click the word(s) you want to remove.';stage.append(s,n)}
function renderChoice(l){const c=document.createElement('div');c.className='choice-zone';l.options.forEach((o,i)=>{const b=token(o,i,true);b.addEventListener('click',()=>{c.querySelectorAll('.token').forEach(x=>x.classList.remove('selected'));b.classList.add('selected');state.choice=o;tone(240,.04)});c.appendChild(b)});stage.appendChild(c)}
function renderReplace(l){const s=document.createElement('div');s.className='sentence-zone';l.sentence.forEach((t,i)=>{const b=token(t,i,true);if(i===0)b.addEventListener('click',()=>{b.textContent=b.textContent===l.tokens[0]?l.tokens[1]:l.tokens[0];state.replace=b.textContent;tone(230,.04)});s.appendChild(b)});const n=document.createElement('div');n.className='annotation';n.textContent='Click the first character to replace it.';stage.append(s,n)}
function result(l){if(l.type==='build')return state.selected.map(x=>x.text);if(l.type==='remove')return l.tokens.filter((_,i)=>!state.removed.has(i));if(l.type==='choice')return state.choice;if(l.type==='replace')return[state.replace||l.sentence[0],...l.sentence.slice(1)]}
function eq(a,b){return Array.isArray(a)&&Array.isArray(b)&&a.length===b.length&&a.every((v,i)=>v===b[i])}
function fail(){return{zh:'文字没有发生正确的变化。再看看它们的结构。',ja:'まだ文字の意味が変わっていない。もう一度。',en:'The room does not react. The arrangement is wrong.',de:'Der Raum reagiert nicht. Die Wortbildung stimmt noch nicht.',fr:"La pièce ne réagit pas. La transformation n'est pas correcte.",es:'La habitación no reacciona. Las palabras todavía no encajan.'}[lang]}
function check(){const l=LEVELS[lang][levelIndex],r=result(l),ok=Array.isArray(l.answer)?eq(r,l.answer):r===l.answer;if(!ok){message.className='message bad';message.textContent=fail();tone(90,.12);return}message.className='message good';message.innerHTML=`<strong>${l.success}</strong><br>${l.explain}`;tone(360,.14);checkBtn.disabled=true;resetBtn.disabled=true;setTimeout(()=>{if(levelIndex<LEVELS[lang].length-1){levelIndex++;renderLevel()}else complete()},1700)}
function complete(){const u=UI[lang];show('complete');applyUI();completeKicker.textContent=u.route;completeTitle.textContent=u.done;completeBody.textContent=u.complete;languageFeature.textContent=u.feature;nextRouteBtn.textContent=u.next;tone(440,.22)}
hintBtn.addEventListener('click',()=>{hintText.hidden=!hintText.hidden;tone(210,.04)});checkBtn.addEventListener('click',check);resetBtn.addEventListener('click',renderLevel);homeBtn.addEventListener('click',()=>{show('menu');document.body.className=''});nextRouteBtn.addEventListener('click',()=>{show('menu');document.body.className=''});soundBtn.addEventListener('click',()=>{soundEnabled=!soundEnabled;if(soundEnabled&&!audioCtx)audioCtx=new(window.AudioContext||window.webkitAudioContext)();applyUI();tone(260,.05)});
buildMenu();show('menu');
